services:
    ######################################################################################
    # RDS (PostgreSQL) Service (user-management-service)
    ######################################################################################
    maybank-rds-user-service:
        image: postgres:latest
        container_name: maybank-rds-user-service
        ports:
            - ${RDS_USER_SERVICE_PORT:-15432}:5432
        environment:
            POSTGRES_DB: ${RDS_SERVICE_NAME:-maybank}
            POSTGRES_USER: ${RDS_SERVICE_USER:-******}
            POSTGRES_PASSWORD: ${RDS_SERVICE_PASS:-******}
        volumes:
            - /tmp/maybank-rds-user-service/data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${RDS_SERVICE_USER:-******} -d ${RDS_SERVICE_NAME:-maybank}"]
            interval: 10s
            retries: 5
    ######################################################################################
    # RDS (PostgreSQL) Service (accounting-management-service)
    ######################################################################################
    maybank-rds-accounting-service:
        image: postgres:latest
        container_name: maybank-rds-accounting-service
        ports:
            - ${RDS_ACCOUNTING_SERVICE_PORT:-25432}:5432
        environment:
            POSTGRES_DB: ${RDS_SERVICE_NAME:-maybank}
            POSTGRES_USER: ${RDS_SERVICE_USER:-******}
            POSTGRES_PASSWORD: ${RDS_SERVICE_PASS:-******}
        volumes:
            - /tmp/maybank-rds-accounting-service/data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${RDS_SERVICE_USER:-******} -d ${RDS_SERVICE_NAME:-maybank}"]
            interval: 10s
            retries: 5
    ######################################################################################
    # ZooKeeper Service (for Kafka accounting-management-service)
    ######################################################################################
    maybank-zookeeper-accounting-service:
        image: wurstmeister/zookeeper
        container_name: maybank-zookeeper-accounting-service
        ports:
            - ${ZOOKEEPER_ACCOUNTING_SERVICE_PORT:-22181}:2181
    ######################################################################################
    # Kafka Service (for accounting-management-service)
    ######################################################################################
    maybank-kafka-accounting-service:
        image: wurstmeister/kafka
        container_name: maybank-kafka-accounting-service
        ports:
            - ${KAFKA_ACCOUNTING_SERVICE_PORT:-29092}:9092
        environment:
#            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${ACCOUNTING_MANAGEMENT_SERVICE_KAFKA_ENDPOINT:-maybank-kafka-accounting-service:29092}
            KAFKA_ADVERTISED_HOST_NAME: ${ACCOUNTING_MANAGEMENT_SERVICE_KAFKA_HOSTNAME:-maybank-kafka-accounting-servic}
            KAFKA_ZOOKEEPER_CONNECT: maybank-zookeeper-accounting-service:2181
            KAFKA_NUM_PARTITIONS: 1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    ######################################################################################
    # Assignment Maybank Micro (user-management-service) Service
    ######################################################################################
    maybank-user-management-service: 
        image: user-management-service:latest
        container_name: maybank-user-management-service
        ports:
            - ${USER_MANAGEMENT_REST_SERVICE_PORT:-18081}:18081
        environment:
            USER_MANAGEMENT_REST_SERVICE_PORT: ${USER_MANAGEMENT_REST_SERVICE_PORT:-18081}
            USER_MANAGEMENT_DATASOURCE_JDBC_URL: ${USER_MANAGEMENT_DATASOURCE_JDBC_URL:-jdbc:postgresql://maybank-rds-user-service:15432/maybank}
            USER_MANAGEMENT_DATASOURCE_USERNAME: ${USER_MANAGEMENT_DATASOURCE_USERNAME:-******}
            USER_MANAGEMENT_DATASOURCE_PASS: ${USER_MANAGEMENT_DATASOURCE_PASS:-******}
            USER_MANAGEMENT_LOGGING_LEVEL: ${USER_MANAGEMENT_LOGGING_LEVEL:-INFO}
        depends_on:
            maybank-rds-user-service:
                condition: service_healthy
        links: 
            - maybank-rds-user-service
    ######################################################################################
    # Assignment Maybank Micro (accounting-management-service) Service
    ######################################################################################
    maybank-accounting-management-service: 
        image: accounting-management-service:latest
        container_name: maybank-accounting-management-service
        ports:
            - ${ACCOUNTING_MANAGEMENT_REST_SERVICE_PORT:-18082}:18082
        environment:
            ACCOUNTING_MANAGEMENT_REST_SERVICE_PORT: ${ACCOUNTING_MANAGEMENT_REST_SERVICE_PORT:-18082}
            ACCOUNTING_MANAGEMENT_DATASOURCE_JDBC_URL: ${ACCOUNTING_MANAGEMENT_DATASOURCE_JDBC_URL:-jdbc:postgresql://maybank-rds-accounting-service:25432/maybank}
            ACCOUNTING_MANAGEMENT_DATASOURCE_USERNAME: ${ACCOUNTING_MANAGEMENT_DATASOURCE_USERNAME:-******}
            ACCOUNTING_MANAGEMENT_DATASOURCE_PASS: ${ACCOUNTING_MANAGEMENT_DATASOURCE_PASS:-******}
            ACCOUNTING_MANAGEMENT_LOGGING_LEVEL: ${ACCOUNTING_MANAGEMENT_LOGGING_LEVEL:-INFO}
            ACCOUNTING_MANAGEMENT_AUTH_BASE_ENDPOINT: ${ACCOUNTING_MANAGEMENT_AUTH_BASE_ENDPOINT:-http://maybank-user-management-service:18081}
            ACCOUNTING_MANAGEMENT_JPA_BATCH_SIZE: ${ACCOUNTING_MANAGEMENT_JPA_BATCH_SIZE:-10}
            ACCOUNTING_MANAGEMENT_JPA_SHOW_SQL_QUERIES: ${ACCOUNTING_MANAGEMENT_JPA_SHOW_SQL_QUERIES:-false}
            ACCOUNTING_MANAGEMENT_SERVICE_MULTIPART_MAX_FILE_SIZE: ${ACCOUNTING_MANAGEMENT_SERVICE_MULTIPART_MAX_FILE_SIZE:-10MB}
            ACCOUNTING_MANAGEMENT_SERVICE_MULTIPART_MAX_REQUEST_SIZE: ${ACCOUNTING_MANAGEMENT_SERVICE_MULTIPART_MAX_REQUEST_SIZE:-100MB}
            ACCOUNTING_MANAGEMENT_SERVICE_DATAFORMATTING_DATE_SIMPLE: ${ACCOUNTING_MANAGEMENT_SERVICE_DATAFORMATTING_DATE_SIMPLE:-yyyy-MM-dd}
            ACCOUNTING_MANAGEMENT_SERVICE_DATAFORMATTING_TIME_SIMPLE: ${ACCOUNTING_MANAGEMENT_SERVICE_DATAFORMATTING_TIME_SIMPLE:-hh:mm:ss}
            ACCOUNTING_MANAGEMENT_SERVICE_DATALIMITER_PAGINATION_PAGESIZE: ${ACCOUNTING_MANAGEMENT_SERVICE_DATALIMITER_PAGINATION_PAGESIZE:-50}
            ACCOUNTING_MANAGEMENT_SERVICE_KAFKA_ENDPOINT: ${ACCOUNTING_MANAGEMENT_SERVICE_KAFKA_ENDPOINT:-maybank-kafka-accounting-service:29092}
            ACCOUNTING_MANAGEMENT_SERVICE_KAFKA_TOPIC: ${ACCOUNTING_MANAGEMENT_SERVICE_KAFKA_TOPIC:-test}
        volumes:
            - /tmp/maybank-accounting-management-service/uploads:/opt/app/uploads
        depends_on:
            maybank-rds-accounting-service:
                condition: service_healthy
        links: 
            - maybank-rds-accounting-service